# Generated by Django 3.2.9 on 2021-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='constituency',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leaderName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='partyName',
            field=models.CharField(choices=[('Pakistan Tehreek-e-Insaf', 'Pakistan Tehreek-e-Insaf'), ('Pakistan Muslim League (N)', 'Pakistan Muslim League (N)'), ('Pakistan Muslim League', 'Pakistan Muslim League'), ('Pakistan Peoples Party', 'Pakistan Peoples Party'), ('Jamaat-e-Islami', 'Jamaat-e-Islami')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbolName',
            field=models.CharField(choices=[('BALA', 'BALA'), ('LOTA', 'LOTA'), ('SHAR', 'SHAR'), ('TEAR', 'TEAR')], max_length=255, unique=True),
        ),
    ]
