# Generated by Django 3.2.9 on 2021-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0002_auto_20211203_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbolImage',
            field=models.ImageField(null=True, upload_to='symbols/'),
        ),
    ]
