# Generated by Django 3.2.9 on 2021-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0002_add_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
