# Generated by Django 3.2.9 on 2021-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0003_alter_symbol_symbolimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='constituency',
        ),
    ]
