# Generated by Django 3.2.9 on 2021-11-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0003_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_Leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.leader'),
        ),
    ]
