# Generated by Django 3.2.9 on 2021-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0004_remove_seat_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seatName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
