# Generated by Django 3.2.9 on 2021-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0004_alter_parties_party_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(choices=[('BALA', 'BALA'), ('LOTA', 'LOTA'), ('SHAR', 'SHAR'), ('TEAR', 'TEAR')], max_length=255)),
                ('symbol_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
