# Generated by Django 3.2.9 on 2021-11-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteing', '0005_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_election',
            name='election_type',
            field=models.CharField(choices=[('MNA', 'MNA'), ('MPA', 'MPA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='parties',
            name='party_Name',
            field=models.CharField(choices=[('Pakistan Tehreek-e-Insaf', 'Pakistan Tehreek-e-Insaf'), ('Pakistan Muslim League (N)', 'Pakistan Muslim League (N)'), ('Pakistan Muslim League', 'Pakistan Muslim League'), ('Pakistan Peoples Party', 'Pakistan Peoples Party'), ('Jamaat-e-Islami', 'Jamaat-e-Islami')], max_length=200),
        ),
        migrations.AlterField(
            model_name='parties',
            name='party_Symbol',
            field=models.CharField(choices=[('BALA', 'BALA'), ('LOTA', 'LOTA'), ('SHAR', 'SHAR'), ('TEAR', 'TEAR')], max_length=200),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voteing.add_election')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voteing.parties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
