# Generated by Django 3.2.9 on 2021-12-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(upload_to='candidate'),
        ),
        migrations.AlterField(
            model_name='voters',
            name='cnic',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
