# Generated by Django 3.2.9 on 2021-11-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0007_candidate_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=255)),
            ],
        ),
    ]
