# Generated by Django 3.2.9 on 2021-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0008_alter_news_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_election',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='add_election',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
