# Generated by Django 3.2.9 on 2021-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0009_auto_20211206_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ManyToManyField(to='voteing.add_election'),
        ),
    ]
