# Generated by Django 3.2.9 on 2021-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0010_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='constituency',
            field=models.CharField(max_length=200),
        ),
    ]
