# Generated by Django 3.2.9 on 2021-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0011_alter_voters_constituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_election',
            old_name='election_rules',
            new_name='electionrules',
        ),
        migrations.RenameField(
            model_name='add_election',
            old_name='end_date',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='add_election',
            old_name='start_date',
            new_name='startdate',
        ),
        migrations.RemoveField(
            model_name='add_election',
            name='election_type',
        ),
        migrations.AddField(
            model_name='add_election',
            name='electiontype',
            field=models.CharField(choices=[('general', 'general'), ('local', 'local')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
