# Generated by Django 3.2.9 on 2021-12-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0012_auto_20211201_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_Symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.symbol'),
        ),
    ]
