# Generated by Django 3.2.9 on 2021-12-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0012_alter_voters_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='electionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.candidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.parties')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.seat')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteing.voters')),
            ],
        ),
    ]
