# Generated by Django 3.2.9 on 2021-12-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0013_alter_parties_party_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_election',
            old_name='electionrules',
            new_name='election_rules',
        ),
        migrations.RenameField(
            model_name='add_election',
            old_name='electiontype',
            new_name='election_type',
        ),
        migrations.RenameField(
            model_name='add_election',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='add_election',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
