# Generated by Django 3.2.9 on 2021-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0014_alter_electionresult_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='Candidate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='party',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='seat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='voter',
            field=models.CharField(max_length=255),
        ),
    ]
