# Generated by Django 3.2.9 on 2021-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0015_auto_20211206_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionReslts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuser', models.CharField(max_length=255)),
                ('Candidate', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('seat', models.CharField(max_length=255)),
            ],
        ),
    ]
