# Generated by Django 3.2.9 on 2021-12-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0016_electionreslts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='electionResult',
        ),
        migrations.AlterField(
            model_name='electionreslts',
            name='vuser',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
