# Generated by Django 3.2.9 on 2021-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0017_auto_20211207_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
