# Generated by Django 3.2.9 on 2021-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0018_alter_news_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
