# Generated by Django 3.2.9 on 2021-12-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0021_updates_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emil', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
    ]
