# Generated by Django 3.2.9 on 2021-12-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteing', '0022_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FileField(upload_to='form/')),
            ],
        ),
    ]
